---
title: 第十二章--通过异常处理错误
author: tongji4m3
top: false
cover: false
coverImg: /images/1.jpg
toc: true
mathjax: false
summary: '<< Java编程思想 >>读书笔记,第十二章--通过异常处理错误。'
categories: Java编程思想
tags:
  - Java基础
  - 异常
  - Exception
abbrlink: bf34118e
date: 2020-10-29 00:00:00
---

> <<Java编程思想>>读书笔记

# 概念

+ 异常通过编译器强制执行的
+ 它往往能够降低错误处理代码的复杂度

## 基本异常

使用`new`在堆上创建异常对象,然后当前的执行路径被终止,并且从当前环境中弹出对异常对象的引用,此时异常处理机制接管程序,将程序从错误状态中恢复,使程序继续运行下去

异常运行我们强制程序停止运行,并告诉我们出现了什么问题,或者强制程序处理问题,并返回到稳定状态

`Throwable`对象是异常类型的跟类

# 捕获异常

+ 如果在方法内部抛出异常,它将在抛出异常的过程中结束
+ 异常可以写入标准错误流`System.err`,他不会被重定向
+ `e.printStackTrace()`打印从方法调用处直到异常抛出处的方法调用序列,默认是被输出到标准错误流
+ `printStackTrace`返回一个由栈轨迹中的元素构成的数组,栈顶是调用序列中的最后一个方法调用

```java
    public static void main(String[] args)
    {
        try
        {
            test();
        }
        catch (Throwable throwable)
        {
            throwable.printStackTrace(System.out);
        }
    }

    public static void test() throws Throwable
    {
        throw new Throwable();
    }
    /*
    java.lang.Throwable
	at com.tongji.MainTest.test(MainTest.java:22)
	at com.tongji.MainTest.main(MainTest.java:12)
     */
```

# 异常声明

+ 如果方法里的代码产生了异常却没有进行处理,编译器会发现这个问题并提醒你:要么处理,要么在异常说明中表明该方法将产生异常
+ 可以声明方法将抛出异常,而实际上不抛出
+ 可以定义接口时预先声明异常,这样接口实现就可以抛出这些预先声明的异常
+ 在编译器被强制检查的异常称为被检查的异常

# Java标准异常

`Throwable`用来表示任何可以作为异常抛出的类,`Error`用来表示编译时和系统错误,`Exception`是可以被抛出的基本类型

## RuntimeException

+ 是Java标准运行时检测的一部分,会自动被虚拟机抛出,不必要声明方法将抛出`RuntimeException`类型的异常
+ 它称为不受检查异常,属于错误,将被自动捕获
+ 该异常通常会穿越所有执行路径直达`main`方法,并在程序退出前调用异常的`printStackTrace`方法
+ `RuntimeException`代表的其实是编程错误,要么是无法预料的错误(如传入`null`引用),程序员应该在代码中检查的错误(数组越界)

# 异常的限制

+ 当覆盖方法时,子类只能抛出在基类方法的异常说明中列出的那些异常,保证了对象的可替换性
+ 异常限制对构造器不起作用,然而因为基类构造器必须被调用,所有派生类构造器的异常说明必须包含基类构造器的异常说明
+ 派生类可以不抛出任何异常,即使它是基类定义的异常
+ 不能基于异常说明来重载方法
+ 一个出现在基类方法的异常说明中的异常,不一定会出现在派生类的异常说明里,即某个特定方法的异常说明的接口变小了,和继承相反

# 构造器

+ 构造器会把对象置为安全的初始状态,但是构造器内部抛出异常,就难受了
+ 对于在构造阶段可能会抛出的异常,并且要求清理的类,最安全的使用方式是嵌套`try`语句
+ 基本规则是,在创建需要清理的对象后,立即进入一个`try-finally`语句块

# 异常匹配

+ 异常在找到匹配的处理程序后,就认为异常得到处理,不再继续查找
+ 只有在你知道如何处理的情况下才捕获异常
+ `main`方法也可以有异常说明,如果使用``Exception``,就传递给了控制台,不需要写`try-catch`语句了

